version: "3.7"

services:
  appsmith-internal-client:
    build: ./app/client/
    env_file: .env
    ports:
      - "8081:3000"
    networks:
      - appsmith
    depends_on:
      - appsmith-internal-server
    
  appsmith-internal-server:
    image: appsmith/appsmith-server:release
    env_file: .env
    environment:
      APPSMITH_REDIS_URL: "redis://redis:6379"
      APPSMITH_MONGODB_URI: "mongodb://mongo:27017/appsmith"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    networks:
      - appsmith
    volumes:
      - /root/appsmith_data/git-storage:/data/git-storage

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=appsmith
    volumes:
      - /root/appsmith_data/mongodb:/data/db
    networks:
      - appsmith

  redis:
    image: redis
    networks:
      - appsmith

networks:
  appsmith:
    driver: bridge